// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfumeStore.Infrastructure.Persistence;

#nullable disable

namespace PerfumeStore.Infrastructure.Migrations
{
    [DbContext(typeof(PerfumeStoreDbContext))]
    [Migration("20260214173404_SetBrandDescriptionLengthToMax")]
    partial class SetBrandDescriptionLengthToMax
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrandDescription")
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Name" }, "IX_Brands")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonPhone")
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("PurchaseInvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SalesInvoiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonPhone");

                    b.HasIndex("PurchaseInvoiceId")
                        .IsUnique()
                        .HasFilter("[PurchaseInvoiceId] IS NOT NULL");

                    b.HasIndex("SalesInvoiceId")
                        .IsUnique()
                        .HasFilter("[SalesInvoiceId] IS NOT NULL");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Expense", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Expenses_ExpenseDate");

                    b.Property<int>("MoneyAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("MoneyAccountID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.MoneyAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("MoneyAccounts");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.MoneyTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_MoneyTransactions_TransferDate");

                    b.Property<int>("FromMoneyAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ToMoneyAccountID")
                        .HasColumnType("int");

                    b.Property<decimal>("TransferAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ID");

                    b.HasIndex("FromMoneyAccountID");

                    b.HasIndex("ToMoneyAccountID");

                    b.ToTable("MoneyTransactions");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PaymentVoucher", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_PaymentVouchers_PaymentVoucherDate");

                    b.Property<int>("MoneyAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("PurchaseInvoiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("MoneyAccountID");

                    b.HasIndex("PurchaseInvoiceID");

                    b.HasIndex("SupplierPhone");

                    b.ToTable("PaymentVouchers");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Person", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Phone");

                    b.ToTable("Persons");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductCategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("ProductCategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("AmountPaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_PurchaseInvoices_InvoiceDate");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SupplierPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("SupplierPhone");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PurchaseInvoiceItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<long>("PurchaseInvoiceID")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("PurchaseInvoiceID");

                    b.ToTable("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.ReceiptVoucher", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_ReceiptVouchers_ReceiptVoucherDate");

                    b.Property<int>("MoneyAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("SalesInvoiceID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CustomerPhone");

                    b.HasIndex("MoneyAccountID");

                    b.HasIndex("SalesInvoiceID");

                    b.ToTable("ReceiptVouchers");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.SalesInvoice", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("AmountPaid")
                        .HasColumnType("int");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_SalesInvoices_InvoiceDate");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerPhone");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.SalesInvoiceItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("SalesInvoiceID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SalesInvoiceID");

                    b.ToTable("SalesInvoiceItems");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("PerfumeStore.Domain.Entities.Person");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Supplier", b =>
                {
                    b.HasBaseType("PerfumeStore.Domain.Entities.Person");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Debt", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Person", "Person")
                        .WithMany("Debts")
                        .HasForeignKey("PersonPhone");

                    b.HasOne("PerfumeStore.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithOne("Debt")
                        .HasForeignKey("PerfumeStore.Domain.Entities.Debt", "PurchaseInvoiceId");

                    b.HasOne("PerfumeStore.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithOne("Debt")
                        .HasForeignKey("PerfumeStore.Domain.Entities.Debt", "SalesInvoiceId");

                    b.Navigation("Person");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Expense", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.MoneyAccount", "MoneyAccount")
                        .WithMany("Expenses")
                        .HasForeignKey("MoneyAccountID")
                        .IsRequired()
                        .HasConstraintName("FK_Expenses_MoneyAccounts1");

                    b.Navigation("MoneyAccount");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("PerfumeStore.Domain.Entities.Inventory", "ProductID")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Products1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.MoneyTransaction", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.MoneyAccount", "FromMoneyAccount")
                        .WithMany("MoneyTransfersFromMoneyAccount")
                        .HasForeignKey("FromMoneyAccountID")
                        .IsRequired()
                        .HasConstraintName("FK_MoneyTransactions_MoneyAccounts1");

                    b.HasOne("PerfumeStore.Domain.Entities.MoneyAccount", "ToMoneyAccount")
                        .WithMany("MoneyTransfersToMoneyAccount")
                        .HasForeignKey("ToMoneyAccountID")
                        .IsRequired()
                        .HasConstraintName("FK_MoneyTransactions_MoneyAccounts");

                    b.Navigation("FromMoneyAccount");

                    b.Navigation("ToMoneyAccount");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PaymentVoucher", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.MoneyAccount", "MoneyAccount")
                        .WithMany("PaymentVouchers")
                        .HasForeignKey("MoneyAccountID")
                        .IsRequired()
                        .HasConstraintName("FK_PaymentVouchers_MoneyAccounts1");

                    b.HasOne("PerfumeStore.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PaymentVouchers")
                        .HasForeignKey("PurchaseInvoiceID")
                        .HasConstraintName("FK_PaymentVouchers_PurchaseInvoices1");

                    b.HasOne("PerfumeStore.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PaymentVouchers")
                        .HasForeignKey("SupplierPhone")
                        .IsRequired();

                    b.Navigation("MoneyAccount");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandID")
                        .HasConstraintName("FK_Products_Brands1");

                    b.HasOne("PerfumeStore.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryID")
                        .IsRequired()
                        .HasConstraintName("FK_Products_ProductCategories1");

                    b.Navigation("Brand");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierPhone")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoices_Suppliers1");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("ProductID")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoiceItems_Products1");

                    b.HasOne("PerfumeStore.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("PurchaseInvoiceID")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoiceItems_PurchaseInvoices1");

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.ReceiptVoucher", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Customer", "Customer")
                        .WithMany("ReceiptVouchers")
                        .HasForeignKey("CustomerPhone")
                        .IsRequired()
                        .HasConstraintName("FK_ReceiptVouchers_Customers1");

                    b.HasOne("PerfumeStore.Domain.Entities.MoneyAccount", "MoneyAccount")
                        .WithMany("ReceiptVouchers")
                        .HasForeignKey("MoneyAccountID")
                        .IsRequired()
                        .HasConstraintName("FK_ReceiptVouchers_MoneyAccounts1");

                    b.HasOne("PerfumeStore.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("ReceiptVouchers")
                        .HasForeignKey("SalesInvoiceID")
                        .HasConstraintName("FK_ReceiptVouchers_SalesInvoices1");

                    b.Navigation("Customer");

                    b.Navigation("MoneyAccount");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.SalesInvoice", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerPhone")
                        .HasConstraintName("FK_SalesInvoices_Customers1");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.SalesInvoiceItem", b =>
                {
                    b.HasOne("PerfumeStore.Domain.Entities.Product", "Product")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("ProductID")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceItems_Products1");

                    b.HasOne("PerfumeStore.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("SalesInvoiceID")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceItems_SalesInvoices1");

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.MoneyAccount", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("MoneyTransfersFromMoneyAccount");

                    b.Navigation("MoneyTransfersToMoneyAccount");

                    b.Navigation("PaymentVouchers");

                    b.Navigation("ReceiptVouchers");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Person", b =>
                {
                    b.Navigation("Debts");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("PurchaseInvoiceItems");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Navigation("Debt");

                    b.Navigation("PaymentVouchers");

                    b.Navigation("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.SalesInvoice", b =>
                {
                    b.Navigation("Debt");

                    b.Navigation("ReceiptVouchers");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Customer", b =>
                {
                    b.Navigation("ReceiptVouchers");

                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("PerfumeStore.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PaymentVouchers");

                    b.Navigation("PurchaseInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
